title: 好墨 Hao.Ink
description: 夏和帆的博客
author: 夏和帆
show_downloads: false
google_analytics: G-YX76K9MB25
theme: jekyll-theme-modernist
github:
  is_project_page: false
plugins:
  - jekyll-feed
  
paginate: 10
paginate_path: /page/:num
